name: ci

on: [push, pull_request, release]

jobs:
  test:
    name: test setup-wabt on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo@${{ github.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: install node n npm
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: audit deps
        run: npm audit
      - name: install deps
        run: npm i
      - name: install wabt
        # with:
        #   version: 1.0.33
        run: |
          node ./main.js
          echo "$HOME/.wabt_1.0.34/bin" >> $GITHUB_PATH

      - name: check a tool
        run: wat2wasm --help
