name: ci

on: [push, pull_request, release]

jobs:
  test:
    name: test setup-wabt on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo@${{ github.ref }}
        uses: actions/checkout@v1.0.0
        with:
          ref: ${{ github.ref }}
      - name: install node n npm
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 19.x
      - name: audit deps
        run: npm audit
      - name: install deps
        run: npm i
      - name: install wabt
        run: node ./main.js
      - name: check a tool
        run: wat2wasm --help
